#Write SQL queries to perform the following tasks using the Sakila database:

#List the number of films per category.
#Retrieve the store ID, city, and country for each store.
#Calculate the total revenue generated by each store in dollars.
#Determine the average running time of films for each category.

use sakila;

select c.name, count(*) from category c 
	INNER JOIN film_category fc 
		ON c.category_id = fc.category_id
group by c.name
order by count(*) desc;

select store_id, c.city, country from store s
	inner join address a
		ON s.address_id = a.address_id
	inner join city c 
		ON a.address_id = c.city_id
	inner join country co 
		ON c.country_id = co.country_id;
 
select sto.store_id, sum(p.amount) from store sto
	inner join customer cu
		on sto.store_id = cu.store_id
    inner join payment p
		on cu.customer_id = p.customer_id
group by sto.store_id
;
        
select c.name, avg(f.length) from film f 
	inner join film_category fc
		on f.film_id = fc.film_id
	inner join category c on fc.category_id = c.category_id
group by c.name;
    